### ISSUE TITLE
Fehler nach neustem Nodejs update

### ISSUE THREAD

**Issue by Trunks1982** [crycode-de/ioBroker.canbus#224]
hi ich habe heute mal mein System auf den neusten Stand gebracht also auch nodejs, nach der Anleitung von Dutchman.
Jetzt bekomme ich diese Fehlermeldung:
adapter "canbus" seems to be installed for a different version of Node.js. Trying to rebuild it... 1 attempt

Weißt du woran das liegt?

Node.js: v18.15.0
NPM: v9.5.0
iobroker Version 6.3.5

**Comment by crycode-de** [comment]
Das ist soweit normal und auch richtig.
Damit der Adapter mit der neuen Version von Node.js laufen kann, muss ein rebuild vom socketcan Modul erfolgen, was der js-controller automatisch macht und eben mit der Meldung anzeigt.
Je nach Performance von deinem System kann das einen Moment dauern und danach sollte der Adapter normal starten.

**Comment by crycode-de** [comment]
Falls das Problem doch weiter besteht meld dich einfach noch mal.
