### ISSUE TITLE
support request

### ISSUE THREAD

**Issue by Dobbiiey** [crycode-de/ioBroker.canbus#225]
Hello crycode-de,
first: congratulation and many thanks for the canbus-adapter.

As ioBroker beginner I needed long time to get it work ;-). Your example config helped a lot to integrate all "my wished functions" of StiebelEltron LWZ 403 SOL.
But now I have questions, I couldn't find the solution by myself.
I hope it is ok to create an GitHub issue ... if not, just tell me a better way...

1. Combination of CAN-signals to one "datapoint". Is there a clever posibility to do it in the adapter ? Currently I have a "blockly-script doing the calculation"
     example of two signals:
     "WM WRG Tag Wh" ->   can0  180   [7]  D2 1E FA 03 AE "readInt16BE(5)"
     "WM WRG Tag kWh" -> can0  180   [7]  D2 1E FA 03 AF "readInt16BE(5)"
2. Currently I querie values by sending in intervalls. I set different intervall values to the single messages. But with lots of values it's not easy not to send in same time lots of requests. How did you do it  with external scripts?

best regards & again: thanks for the really good adapter!
Tobi

**Comment by Dobbiiey** [comment]
Hallo,
### sharedData
sharedData funktioniert wunderbar bei mir.
So habe ich in einem "parser-Eintrag" die Werte:
"WM WRG Tag Wh" -> can0 180 [7] D2 1E FA 03 AE ...
"WM WRG Tag kWh" -> can0 180 [7] D2 1E FA 03 AF ...
gleich verrechnen können. Klar, 03ae sollte immer von 03af ankommen...

`if ((buffer[0] === 0xD2) && (buffer[2] === 0xFA) && (buffer[3] === 0x03) && (buffer[4] === 0xae)) {
  sharedData.d03ae = buffer.readInt16BE(5)/1000;
}
if ((buffer[0] === 0xD2) && (buffer[2] === 0xFA) && (buffer[3] === 0x03) && (buffer[4] === 0xaf)) { 
  if (typeof sharedData.d03ae !== 'undefined') {
    value = buffer.readInt16BE(5) + sharedData.d03ae;
  } 
}`

Falls ich nichts anderes falsch gemacht habe: Dabei ist aufzupassen, dass die Bez. des sharedData-Objekts nicht schon vergeben ist. Bei mir hat 03ae nicht funktioniert, aber d03ae (im LOG wird entsprechend auf ein Problem hingewiesen).
Mit getStateAsync hab ich mich nicht beschäftigt ;-).

### "gleiche Intervalle"

Das Thema "gleiche Intervalle" ist für mich leider noch nicht abgeschlossen. Nach Einstellung von 300000 oder 600000 oder 3600000 ms für die Anfragen scheinen diese "fast zeitgleich" losgeschickt zu werden:
![image](https://user-images.githubusercontent.com/124839322/232156857-af5eabf4-4c25-48c1-b5bb-ecfae2e10149.png)

Das führt dazu, dass die Antworten nicht mehr ankommen bzw. nicht gesendet werden:
![image](https://user-images.githubusercontent.com/124839322/232156693-f442165e-1df6-43ba-80eb-2623173e9c45.png)

Vorerst werde ich besser wieder auf meine selbst kreierten Zufalls-Zahlen verbunden mit 2x wöchentlichen Restart des Adapters zurück wechseln.
Hast du noch Ideen hierzu ?
Ein weiterer Aspekt: Z.B. könnte für mich interessant werden immer kurz vor 0:00Uhr die "Tages-Summen" abzufragen, anstatt alle 10min ;-)
Was wäre hierfür die Empfehlung ?

tausend Dank für die Geduld & viele Grüße

**Comment by crycode-de** [comment]
### sharedData

Dass 03ea in `sharedData` nicht funktioniert ist richtig und eine "Limitierung" von JavaScript selbst.
Einfach gesagt: Variablennamen müssen (bis auf wenige Ausnahmen) immer mit einem Buchstaben anfangen.

### gleiche Intervalle

Hmm... hier würde ich vermuten, dass die Steuerung auf der Gegenseite vielleicht nicht mit so vielen Anfragen in kurzer Zeit zurecht kommt und einen Großteil dann ignoriert, da irgendein interner Empfangs-Buffer voll läuft.

In dem Fall wäre es wahrscheinlich das sauberste selbst in ioBroker ein Script im JavaScript-Adapter zu erstellen, dass zu den gewünschten Zeitpunkten die Abfrage-States triggert, also den Wert `true` rein schreibt.
Damit könnte man dann z.B. immer 10 Anfragen triggern, ein paar Sekunden warten, dann die nächsten 10, usw.. Wie viele Anfragen auf einmal gehen müsste man wahrscheinlich einfach ausprobieren.
Bei Bedarf kann ich dir dazu auch ein kurzes Beispielscript erstellen.

Für die Abfrage kurz vor 0:00 Uhr wäre auch ein eigenes Script die einfachste Lösung.

**Comment by Dobbiiey** [comment]
> Dass 03ea in `sharedData` nicht funktioniert ist richtig und eine "Limitierung" von JavaScript selbst.
> Einfach gesagt: Variablennamen müssen (bis auf wenige Ausnahmen) immer mit einem Buchstaben anfangen.

Spätestens jetzt bin ich wohl als Maschinenbauer und "VBS/VBA-Hobby-scripter" geoutet...
;-)

Gut, ich geh den Weg zum JavaScript. Dein Angebot ein Beispielscript zu erstellen ist total nett, aber bitte nur, wenn es nicht zu aufwendig ist. Ansonsten würde ich das mit googlen etc. hinbekommen ;-)
Vielen Dank

**Comment by crycode-de** [comment]
Kein Problem 😉

Hier ein Beispiel zum Abfragen (nicht getestet, aber sollte so funktionieren):
```js
// Liste der IDs, die regelmäßig abgefragt werden sollen
const ids = [
  '0924',
  '0925',
  '0928',
  '0929',
  '092a',
  // ...
];

// Liste der IDs, die kurz vor Mitternacht abgefragt werden sollen
const ids_midnight = [
  '0924',
  '0925',
  // ...
];

// Wie viele Anfragen zeitgleich gesendet werden sollen
const at_once = 5;

// Millisekunden die nach dem Senden der zeitgleichen Anfragen gewartet werden soll
const wait_time = 1000;

// ID der ioBroker States zum Abfragen, aber ohne die letzte Parser-ID
const state_id_base = 'canbus.0.680.';

/**
 * Funktion um die angegeben Zeit zu warten.
 * @param time Wartezeit in Millisekunden
 */
async function wait (time) {
  return new Promise((resolve) => {
    setTimeout(resolve, time);
  });
}

/**
 * Funktion um die Anfragen zu senden und dabei entsprechend zu warten.
 * @param request_ids Array mit den IDs die abgefragt werden sollen.
 */
async function send_requests (request_ids) {
  // Kopie des Arrays erstellen, um das ursprüngliche nicht zu verändern
  request_ids = [...request_ids];

  // Schleife solange nicht alle IDs abgearbeitet sind
  while (request_ids.length > 0) {
    
    // Schleife für die Anzahl der IDs die gleichzeitig gesendet werden sollen
    for (let x = 0; x < at_once; x++) {
      // erste ID aus Array holen
      const id = request_ids.shift();
      
      // prüfen ob leer, wenn ja abbrechen
      if (id === undefined) {
        break;
      }
  
      // den State auf true setzen mit ack=false
      await setStateAsync(`${state_id_base}${id}`, true, false);
    }

    // warten
    await wait(wait_time);
  }
}

// Zeitplan zum Abfragen
// siehe https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#schedule
// 0 */5 * * * * => Alle 5 Minuten
// 0 */10 * * * * => Alle 10 Minuten
schedule('0 */5 * * * *', () => {
  send_requests(ids);
});

// Zeitplan zum Abfragen bestimmter IDs kurz vor Mitternacht
schedule('59 59 23 * * *', () => {
  send_requests(ids_midnight);
});

```

**Comment by Dobbiiey** [comment]
Respekt! & Vielen Dank (mein Skript hätte, wenn es nach Wochen fertig gewesen wäre, deinem nicht ähnlich gesehen ;-))
