### ISSUE TITLE
Feature Enhancement config "Modus SG abfragen (fa0694)

### ISSUE THREAD

**Issue by alex030** [crycode-de/ioBroker.canbus#227]
Hi,

I am missing the set option for fa0694. 
"Modus SG abfragen (fa0694)" works as expected. But I am missing the set option for the "Modus SG setzen (xxxx)". 

Can this please be enhanced in the config file. If I could deliver any necessary info, just let me know. 

Thanks in advance
Alex

**Comment by crycode-de** [comment]
Hi, I've added `fa0694-set` (Modus SG setzen) to the Rotex HPSU latest config.
Please check if it's working as intended.
