### ISSUE TITLE
Warning at adapter install

### ISSUE THREAD

**Issue by KalaNagHTD** [crycode-de/ioBroker.canbus#233]
When installing the adapter I get the following message:

"npm warn deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm."

**Comment by crycode-de** [comment]
Thank you for reporting this.

For now there isn't any real security issue for ioBroker.canbus unless you are using some very strange custom parser scripts.
The vm2 module is only used to run the custom parser scripts in an isolated environment.

I'll check for the next minor release, if this can be done without vm2 or if it's required at all.

**Comment by KalaNagHTD** [comment]
Thank you for the quick response and clarification!
I look forward using your great software with my Daikin/Rotex heat pump.

Karl

**Comment by crycode-de** [comment]
The deprecated vm2 module is now removed in v2.0.0 of the adapter :)
